theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  search: {}

markdown_extensions:
  admonition: {}
  attr_list: {}
  def_list: {}
  tables: {}
  toc:
    permalink: true
  pymdownx.details: {}
  pymdownx.superfences: {}
  pymdownx.inlinehilite: {}
  pymdownx.snippets: {}