#!/bin/bash

if [[ $(which uv) == "" ]]; then
    echo "[ERROR] uv is not installed. Please install uv first."
    echo "[INFO] Command: curl -LsSf https://astral.sh/uv/install.sh | sh"
    exit 1
fi

uv sync --active --quiet

export UNIBIT_ROOT=$(git rev-parse --show-toplevel)
