#!/bin/bash

if [[ $(which uv) == "" ]]; then
    echo "[ERROR] uv is not installed. Please install uv first."
    echo "[INFO] Command: curl -LsSf https://astral.sh/uv/install.sh | sh"
    exit 1
fi

PROMPT=unibit
export UV_PROJECT_ENVIRONMENT=.$PROMPT
uv venv $UV_PROJECT_ENVIRONMENT --prompt $PROMPT --clear
source $UV_PROJECT_ENVIRONMENT/bin/activate
uv sync --active --quiet

export UNIBIT_ROOT=$(git rev-parse --show-toplevel)
