#!/bin/bash

if [[ $(which uv) == "" ]]; then
    echo "[ERROR] uv is not installed. Please install uv first."
    echo "[INFO] Command: curl -LsSf https://astral.sh/uv/install.sh | sh"
    exit 1
fi

PROMPT=hcv
export UV_PROJECT_ENVIRONMENT=.$PROMPT
uv venv $UV_PROJECT_ENVIRONMENT --prompt $PROMPT --clear
source $UV_PROJECT_ENVIRONMENT/bin/activate
uv sync --active --quiet

# Enable command-line autocompletion for the `liver` command.
eval "$(register-python-argcomplete hcv)"

export UNIBIT_CW_ROOT=$(git rev-parse --show-toplevel)/CourseWork
